### ISSUE TITLE
Including GraphicsMagick++ flags into node makefile

### ISSUE THREAD

**Issue by MichelPater** [zeitungen/node-rpi-rgb-led-matrix#2]
Hello,

I was wondering how I would go about adding the GraphicsMagick++ flags from the hzeller makefile into the node makefile. My knowledge is still pretty limited but as I understand it GraphicsMagick++ only gets build when the flags are added. Any advice would be greatly appreciated!

p.s. Love the project!

**Comment by hzeller** [comment]
What exactly do you want to do ? Linking the library will not buy you anything.
In the rpi-rgb-led-matrix, this library is used to read and decode images in a standalone program (led-image-viewer), but it is not needed for any functionality of the LED library nor does it add any functionality.

If you want to decode images, you need a whatever other node libraries are available to do that task.

**Comment by MichelPater** [comment]
I was hoping to add the functionality of your standalone program to the core of this library. I basically have added a lot of functionality / logic to the /master/src/ledmatrix.cc  file (which I am now seeing is quite poor on my part). I basically want to be able to include the functionality in the ledmatrix.cc file so I can easily decode and play animated gifs. Again I am now seeing what a mess my code has become, but I still would like to know how I would go about adding the functionality of GraphicsMagick++ to /master/src/ledmatrix.cc.

**Comment by zeitungen** [comment]
Hi,

Like @hzeller said, I guess you can find image decoder from npm.
And it's maybe better to separate image decoding and displaying:
* A decoder library which can give you a pixel image buffer
* A library used to display pixels into a led matrix (this one ;))
* An another piece of codes that links the two previous parts (maybe a future new library ;))

In this way, there is a nodejs module called `gm` who have image magick features: https://www.npmjs.com/package/gm

By the way, if you want to handly link imagemagick to your fork of this project, I can try to help you.

First, for compiling new nodejs native module, we use node-gyp (https://www.npmjs.com/package/node-gyp) and it uses the gyp syntax for the makefile (https://gyp.gsrc.io/docs/LanguageSpecification.md). The makefile in nodejs native module is usually `binding.gyp`.

In this file, for my module, we have 2 targets. The first one is my nodejs binding, the second one is the led-matrix from @hzeller. If you want add IageMagick to the nodejs binding (the `src/ledmatrix.cc` file), you have to add defines and other stuff for the first target (`node-rpi-rgb-led-matrix`).

**Comment by MichelPater** [comment]
My node-gyp file now looks like this:
```
{
	"targets": [
		{
            "target_name": "node-rpi-rgb-led-matrix",
            "sources": [ "src/base.cc", "src/ledmatrix.cc" ],
            "dependencies": [ "./binding.gyp:rpi-rgb-led-matrix" ],
            "include_dirs": [ "./external/matrix/include", "./include/" ],
                 "defines": ["GraphicsMagick++-config", "--cppflags", "--cxxflags"],
                 "libraries": ["GraphicsMagick++-config", "--ldflags", "--lib"]
        },
		{
			"target_name": "rpi-rgb-led-matrix",
			"type": "static_library",
			"sources": ["external/matrix/lib/bdf-font.cc",
				"external/matrix/lib/framebuffer.cc", "external/matrix/lib/gpio.cc",
				"external/matrix/lib/graphics.cc", "external/matrix/lib/led-matrix.cc",
				"external/matrix/lib/thread.cc", "external/matrix/lib/transformer.cc"],
			"libraries": ["-lrt", "-lm", "-lpthread"],
			"defines": ["RGB_SLOWDOWN_GPIO=2"],
			"include_dirs": [ "external/matrix/include" ],
	        "direct_dependent_settings": {
	            "include_dirs": [ "external/matrix/include" ]
	        }
		}
	]
}
```
Except It now won't build, the command output is as follows:

```
pi@raspberrypi ~/node_modules/node-rpi-rgb-led-matrix $ sudo node-gyp build                                                                                  gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.10.2 | linux | arm
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/pi/node_modules/node-rpi-rgb-led-matrix/build'
  ACTION Regenerating Makefile
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/bdf-font                                                                             .o
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/framebuf                                                                             fer.o
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/gpio.o
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/graphics                                                                             .o
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/led-matr                                                                             ix.o
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/thread.o
  CXX(target) Release/obj.target/rpi-rgb-led-matrix/external/matrix/lib/transfor                                                                             mer.o
  AR(target) Release/obj.target/rpi-rgb-led-matrix.a
  COPY Release/rpi-rgb-led-matrix.a
  CXX(target) Release/obj.target/node-rpi-rgb-led-matrix/src/base.o
<command-line>:0:15: warning: missing whitespace after the macro name
<command-line>:0:1: error: macro names must be identifiers
<command-line>:0:1: error: macro names must be identifiers
node-rpi-rgb-led-matrix.target.mk:99: recipe for target 'Release/obj.target/node                                                                             -rpi-rgb-led-matrix/src/base.o' failed
make: *** [Release/obj.target/node-rpi-rgb-led-matrix/src/base.o] Error 1
make: Leaving directory '/home/pi/node_modules/node-rpi-rgb-led-matrix/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/                                                                             lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:757:                                                                             12)
gyp ERR! System Linux 4.1.7-v7+
gyp ERR! command "node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/pi/node_modules/node-rpi-rgb-led-matrix
gyp ERR! node -v v0.10.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by MichelPater** [comment]
I think I might actually have solved it, I took a look at this project's binding.gyp file: https://github.com/networkimprov/node-graphicsmagick. Which led me to change my binding.gyp to the following: 

```
{
	"targets": [
		{
	        "target_name": "node-rpi-rgb-led-matrix",
	        "sources": [ "src/base.cc", "src/ledmatrix.cc"],
	        "dependencies": [ "./binding.gyp:rpi-rgb-led-matrix" ],
	        "include_dirs": [ "./external/matrix/include", "./include/" ],
			"link_settings": {
				"libraries": [ "<!(GraphicsMagick++-config --libs)" ]
			  },
			"ldflags": [ "<!(GraphicsMagick++-config --ldflags)" ],
			"cflags_cc": [ "<!(GraphicsMagick++-config --cppflags)", "<!(GraphicsMagick++-config --cxxflags)" ]

		},
		{
			"target_name": "rpi-rgb-led-matrix",
			"type": "static_library",
			"sources": ["external/matrix/lib/bdf-font.cc",
				"external/matrix/lib/framebuffer.cc", "external/matrix/lib/gpio.cc",
				"external/matrix/lib/graphics.cc", "external/matrix/lib/led-matrix.cc",
				"external/matrix/lib/thread.cc", "external/matrix/lib/transformer.cc"],
			"libraries": ["-lrt", "-lm", "-lpthread"],
			"defines": ["RGB_SLOWDOWN_GPIO=2"],
			"include_dirs": [ "external/matrix/include" ],
	        "direct_dependent_settings": {
	            "include_dirs": [ "external/matrix/include" ]
	        }
		}
	]
}
```

Honestly I'm unsure what the syntax does but I builds like a charm so that's nice :). Anyway thanks for the help and thanks for making these awesome libraries @hzeller & @zeitungen!

**Comment by zeitungen** [comment]
Nice if you can progress.
