### ISSUE TITLE
Update readme with more example 

### ISSUE THREAD

**Issue by ArcaneDiver** [zeitungen/node-rpi-rgb-led-matrix#22]
Pls may you add example for scroll some text or display and image? I'm not really skillful the a help will be more appreciated.
Thanks.

**Comment by zeitungen** [comment]
Hello !

This project is not maintained anymore.
Please, look at https://github.com/easybotics/node-rpi-rgb-led-matrix
It's a fork from this project and it's maintained.

Good luck ;-)
