### ISSUE TITLE
Trouble compiling with node-gyp

### ISSUE THREAD

**Issue by felixmc** [zeitungen/node-rpi-rgb-led-matrix#3]
I have a Raspberry Pi 2 Model B running latest Raspbian, Node.js v4.2.2, and node-gyp v3.2.1

When I try installing `node-rpi-rgb-led-matrix` via npm I get the following error: https://www.dropbox.com/s/5vbfcsa38wffwwo/Screenshot%202016-01-17%2012.31.16.png?dl=0

Here is the associated `npm-debug.log`: http://pastebin.com/mBr7AGP2

Afterwards I tried cloning the project in `node_modules` and building it manually with node-gyp, but it failed again with a different error code. Here's what the output looked like: https://www.dropbox.com/s/jhus8ciayk08kce/Screenshot%202016-01-17%2012.38.21.png?dl=0

Seems like it might be a problem with the project, but it could also be something specific to my environment. Let me know if there's anything I can do to help resolve this!

**Comment by phuongvu** [comment]
You might want to downgrade your Node to v0.10.x.

**Comment by felixmc** [comment]
@phuongvu thank you! after downgrading node to v0.10.x the package works via both `node-gyp` and `npm install`.

Perhaps this dependency should be expressed in the README as well as `package.json` with something like `{ "engines" : { "node" : ">=0.10.3 <0.12" } }`

**Comment by phuongvu** [comment]
@felixmc I think there is a need to update the code so that it works with node v0.12, v4 and v5. The API changes for native addons introduced in v0.12.x and the newer versions break the build.

https://nodejs.org/api/addons.html
https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/

**Comment by zeitungen** [comment]
Thanks for the feedback !
I only try with node 0.10.x because my environnement require for now the 0.10.x (hello http://timesquair.io/).
But I guess, I can, or something else, start to adapt this to node > 0.10.x and see if it can keep retrocompatibility to 0.10.x.

**Comment by sebleedelisle** [comment]
I've actually got this code working with node 5.4.1 but obviously this breaks in older versions. I'll take a look at implementing NAN - if it's easy then I'll do it and PR. Thanks for a great library!

**Comment by zeitungen** [comment]
I've merged PR from @sebleedelisle, now, you can run this module with nodejs >0.10.x.
Please, give me some feedback about this new updates. If no problem, I'll update the npm package and publish new one.

**Comment by pfraze** [comment]
I had the original issue. I checked out the repo to get latest, and it worked for me :+1:

**Comment by zeitungen** [comment]
I think if nobody else report a problem on this issue, I can close it.
Thanks again for feedbacks.

**Comment by sebleedelisle** [comment]
Thanks Maxime!
