### ISSUE TITLE
Port BDF font support

### ISSUE THREAD

**Issue by TrevorSayre** [zeitungen/node-rpi-rgb-led-matrix#7]
At the moment it's a pain to write text. The external library used by this project supports drawing text with included BDF files.

https://github.com/hzeller/rpi-rgb-led-matrix/blob/90283819e5c3a5180510e9576f78dd7b32a8e6a9/lib/bdf-font.cc

**Comment by zeitungen** [comment]
I think it's not the job to the ledmatrix library to write text. It's too specific.
I guess it's to a specific library to implement this functionality (transform text to something drawable).

I'm working on a functions to draw and scroll "pictures" (pixels buffer with width and height).
So, when this functionnalities will be available, you can easily draw pictures or text pictures generated by third-parties library (like a text to pixels library).
