### ISSUE TITLE
set brightness?

### ISSUE THREAD

**Issue by roykolak** [zeitungen/node-rpi-rgb-led-matrix#8]
Is that supported? Thanks!

**Comment by zeitungen** [comment]
This function is not binded to js yet.
But if you really need it, feel free to implement this functionnality and do a PR to share it ;)

**Comment by roykolak** [comment]
on it! expect something later tonight

**Comment by VictorioBerra** [comment]
@roykolak did you ever get brightness implemented?

**Comment by roykolak** [comment]
@VictorioBerra I actually just ended up shading the color value. Something like this:
https://gist.github.com/roykolak/9604140af3214dfffd13d5d7950ab524

**Comment by VictorioBerra** [comment]
Thanks! Does that achieve the same result?

**Comment by roykolak** [comment]
yep, it does
